name: AppScan CodeSweep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
        id: codesweep
        with:
          output-format: sarif
          status: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASOC_KEY: ${{ secrets.ASOC_KEY }}
          ASOC_SECRET: ${{ secrets.ASOC_SECRET }}

      - name: Debug SARIF file
        run: |
          ls -R AppScanCodeSweep/sarif
          head AppScanCodeSweep/sarif/output.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: AppScanCodeSweep/sarif/output.sarif
