- name: Run AppScan CodeSweep
  uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
  with:
    status: true
    output-format: sarif
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ASOC_KEY: ${{ secrets.ASOC_KEY }}
    ASOC_SECRET: ${{ secrets.ASOC_SECRET }}

- name: Upload CodeSweep report
  uses: actions/upload-artifact@v3
  with:
    name: codesweep-report
    path: AppScanCodeSweep/sarif/output.sarif
